### ISSUE TITLE
Publish cabinet on nest.land

### ISSUE THREAD

**Issue by martonlederer** [dan-online/cabinet#6]
Hey, I love the concept of this module, it makes handling files so much easier. I'm a bit sceptical, so I like to be safe when using modules with module imports, and it would be great to see this package published to https://nest.land. It's a block chain based module registry, where if you publish a release, it can never be removed again. It would give me and probably others confidence that the package will always be there, no matter what :)

**Comment by dan-online** [comment]
Added in [[85791d2](https://github.com/dan-online/cabinet/commit/b4345b65b1ac910ab970e2813150251a585791d2)] although I would like to say the files part of configuration was quite annoying and should allow using ``.`` or ``*``
